-- 此迁移原有的 DBA 级操作(创建 starlens_ai_readonly 角色 + RLS 策略)已移至
-- apps/web/dba/0006_ai_readonly_role_and_rls.sql,由数据库超管单独执行。
--
-- 原因:CREATE ROLE / GRANT ROLE / ALTER ROLE 需要 CREATEROLE 权限,而应用迁移
-- 用户(DATABASE_URL 中的用户)出于最小权限原则不具备该权限,留在 drizzle 迁移里
-- 会导致 `drizzle-kit migrate` 失败。
--
-- 本文件保留为空操作,以维持 drizzle 迁移序号和 __drizzle_migrations 记录的一致性。
-- 新环境部署时:先用超管执行 dba/0006 脚本,再跑 drizzle 迁移(此文件为空操作)。
-- 详见部署文档"DBA 脚本"小节。
-- (此文件不包含任何 SQL 语句,故意留空。)
